apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: 975050024946.dkr.ecr.us-west-1.amazonaws.com/hari-backend-repo:latest

          ports:
            - containerPort: 3003

          env:
            - name: MONGO_URI
              value: "mongodb+srv://hari-mern:YOURPASSWORD@cluster0.wrkbfzu.mongodb.net/streaming"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP

  selector:
    app: backend

  ports:
    - name: http
      port: 3003
      targetPort: 3003
